// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVUJwZHob7_QL1Y46VtX_adavvJ47E0Y',
    appId: '1:751042445266:web:119f37c913fa1b72ee120b',
    messagingSenderId: '751042445266',
    projectId: 'flutter-mango',
    authDomain: 'flutter-mango.firebaseapp.com',
    storageBucket: 'flutter-mango.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKB1iZ5EIUbf3VSgaXyOiVT7Ev9VoHgeA',
    appId: '1:751042445266:android:5ab5150049a7a147ee120b',
    messagingSenderId: '751042445266',
    projectId: 'flutter-mango',
    storageBucket: 'flutter-mango.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlHO3moBiPGqx6RF013PaAsbsSn0YbJgU',
    appId: '1:751042445266:ios:53560d4afbf219feee120b',
    messagingSenderId: '751042445266',
    projectId: 'flutter-mango',
    storageBucket: 'flutter-mango.appspot.com',
    iosBundleId: 'com.workwise.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlHO3moBiPGqx6RF013PaAsbsSn0YbJgU',
    appId: '1:751042445266:ios:4589159a8597633cee120b',
    messagingSenderId: '751042445266',
    projectId: 'flutter-mango',
    storageBucket: 'flutter-mango.appspot.com',
    iosBundleId: 'com.WorkWise.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsVUJwZHob7_QL1Y46VtX_adavvJ47E0Y',
    appId: '1:751042445266:web:dde1cec9e15450e9ee120b',
    messagingSenderId: '751042445266',
    projectId: 'flutter-mango',
    authDomain: 'flutter-mango.firebaseapp.com',
    storageBucket: 'flutter-mango.appspot.com',
  );

}